### ISSUE TITLE
Eurythmia Evolution roadmap

### ISSUE THREAD

**Issue by paly2** [MT-Eurythmia/Eurythmia-Evolution#1]
# Mods sur le serveur
si coché: déjà ajouté dans le dépôt
si pas coché: pas encore ajouté

## Fournis avec minetest_game:

- [x] beds
- [x] boats
- [x] bones
- [x] bucket
- [x] carts
- [x] creative
- [x] default
- [x] doors
- [x] dye
- ~~farming~~ (The farming redo mod is loaded instead)
- [x] fire
- [x] flowers
- [x] give_initial_stuff
- [x] killme
- [x] screwdriver
- [x] sethome
- [x] sfinv
- [x] stairs
- [x] tnt
- [x] vessels
- [x] walls
- [x] wool
- [x] xpanes

## Autres mods:

- [x] 3d_armor
- [x] areas
- [x] automappercolors
- [x] autoshutdown
- [x] babelfish
- [x] everamzah-books
- [x] broomstick
- [x] brush
- [x] more_chests
- [x] christmas_craft 
  * [ ] add a setting to deactivate crafts
- [x] death_messages
  * [ ] Change messages
- [x] easyvend
- [x] email
- [x] fail
- [x] first_hour
  * [x] change spawn point position
- [ ] fishing
- [x] gravitysuit
- [x] h2omes
- [x] hbarmor
- [x] hbhunger
- [x] hopper
- [x] hudbars
- [x] irc
  * [x] Further configuration is required. We need to decide for a channel name
- [x] jumping
- [x] landcraft
- [x] lavasuit
- [x] mapfix
- [x] maptools
- ~~markers~~
- [x] mesecons
- [x] metatools
- [x] misc
  * [x] Needs a few more changes.
- [x] mob_horse
- [x] mobs
  * [x] Add a lifetimer to NPCs
- [x] mobs_animal
- [x] mobs_monster
- [x] mobs_npc
- [x] moremesecons
- ~~moreores~~ ❌ 
- [x] mtsatellite
- [x] names_per_ip
- [x] news
- ~~nyantools~~
- ~~pbj_pup~~
- [x] pvpplus
- [x] pw_like
- [x] serveressentials
- [x] shields
- [x] signs_lib
- ~~sneak_glitch~~
  * [x] Must be merged into misc
- [x] sprint
- [x] staffmagic
- [x] stained_glass
- [x] throwing
- [x] throwing_arrows
- torch May not be kept. We'll see later ⌛️ 
- [x] travelnet
  * [ ] Make the craft more expensive
- [x] treecapitator
- [x] u_skins
  * [x] Re-add custom skins, and remove transparent skins
- [x] unified_inventory
- [x] vector_extras
- [x] wieldview
- [x] worldedit
- [x] xban2
  * Temporaire. Devrait être remplacé par [Umabis](https://github.com/MT-Eurythmia/Umabis)
- ~~xdecor~~ ❌  [Homedecor](https://forum.minetest.net/viewtopic.php?f=11&t=2041) 🆕 

Mapgenerator: Carpathian

Mapgen mods to be *added*:

- [X] [Ethereal](https://forum.minetest.net/viewtopic.php?f=11&t=14638)
  - desactivate fiery (lava biome)
- [X] [Plantlife](https://forum.minetest.net/viewtopic.php?t=3898)
- [X] [More tree](https://forum.minetest.net/viewtopic.php?t=4394)

Mods à considerer/tester ?

- ~~[Ma & Pop's furniture](https://forum.minetest.net/viewtopic.php?f=9&t=17421)~~ ❌ [Homedecor](https://forum.minetest.net/viewtopic.php?f=11&t=2041)
- [x] [Unified Inventory Plus](https://forum.minetest.net/viewtopic.php?f=9&t=16615)
- ~~[Clay crafter](https://forum.minetest.net/viewtopic.php?t=13992)~~
- [x] [Protector](https://forum.minetest.net/viewtopic.php?id=4212)
- [ ] [Workbench](https://github.com/minetest-mods/workbench) **Custom fork indispensable**
- ~~[Enchanting](https://github.com/minetest-mods/enchanting) **Custom fork indispensable**~~ ❌
- [x] [Technic Chests](https://github.com/minetest-mods/technic/tree/master/technic_chests)
- ~~[soccer](https://forum.minetest.net/viewtopic.php?t=6104)~~
- [X] [Homedecor](https://forum.minetest.net/viewtopic.php?f=11&t=2041)

4. moderation/organisation:
- Garde t'on un spawn dans les aires ?
- Créer une grande zone de spawn avec foret, champs publique, commerce ...
- Pour le champs est la foret public je propose de nommer des joueurs responsable qu'on testerait du coups pour êtres modo

j’ajouterai vos proposition au fur et a mesure.

**Comment by Grossam** [comment]
Sur Ilune il y a deux petits mods bien sympa (mais je n'ai pas les noms…)

Un qui émet un petit bip dans le client d'un joueur quand son pseudo apparaît dans le chat (idéal pour attirer l'attention).

L'autre permet d'avoir de la lumière en tenant une torche à la main.

**Comment by Grossam** [comment]
Quelques suggestions de mods : handglider (je t'en ai parlé in game) et toolranks (la version modifiée par mes soins), more_farming, diet (qui oblige à varier sa nourriture, sinon elle ne nourrit plus…)

Un mod de commerce serait bien aussi. Global exchange le semble un bon candidat : il permet aux joueurs d'établir leur propres prux (offre, demande, tout ça…) ; tu peux l'essayer sur le serv de sys4.

Et pourquoi ne pas prévoir des stacks de plus de 99 pour certains petits items (sticks, leaves…)

**Comment by Grossam** [comment]
Deux idée de mods : cottage qui permet des aménagement pour une ferme à l'ancienne (les joueurs aiment bien ce qui fait contes de fées) et le mod qui permet la clay colorée (peut-être en ajoutant aussi la machine à clay de sys4 pour éviter les griefs de paysage ?).

Introduire un nouveau mod de temps à autres est une bonne façon de maintenir l'intérêt des joueurs ;-)

**Comment by paly2** [comment]
Bonne idée, j'ajouterai très rapidement cottage et baked clay, il faudra que je teste si l'enclume de cottage est compatible avec toolranks
